RIA-8273 Print and send hearing bundle - WA task
hmcts/ia-wa-post-deployment-ft-tests pull request #140
Opened 2024-05-14 15:47 UTC by javierhmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RIA-8273

### Change description ###

Print and send hearing bundle - WA task

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-05-15 11:07 UTC, ThomasKKC requested changes

2024-05-15 11:07 UTC, ThomasKKC commented on src/functionalTest/resources/scenarios/ia/IA-RIA-8273-generateHearingBundle-should-create-a-printAndSendHearingBundle-task.json
> +              "NewStateId": "finalBundling",
Check the correct state here.

2024-05-16 15:59 UTC, ThomasKKC requested changes

2024-05-16 15:59 UTC, ThomasKKC commented on src/functionalTest/resources/scenarios/ia/IA-RIA-8273-generateHearingBundle-should-create-a-printAndSendHearingBundle-task.json
> +                "name": "Print and send Hearing Bundle",
Remember to update the name here too.

2024-05-16 16:01 UTC, ThomasKKC approved these changes

2024-05-17 08:22 UTC, colmlynch60 approved these changes
LGTM

2024-05-17 08:22 UTC, merged